name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.14.1"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: node.js ${{ matrix.node }} test in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: |
          node -v
          npm -v
          yarn --version

      - name: Install
        run: |
          yarn

      - name: Compile
        run: |
          yarn run build

      - uses: actions/upload-artifact@v1
        if: runner.os == 'linux'
        with:
          name: package
          path: ./dist

  release:
    runs-on: ubuntu-latest
    name: "Release to vscode market and github"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: package

      - name: Deploy to gh-pages branch
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: ./dist
          GH_PAT: ${{ secrets.GH_PAT }}